-- Database Schema & Seed Data for Portfolio
-- Generated on: 2026-06-18T07:26:41.926Z

-- =========================================================
-- 1. CERTIFICATIONS TABLE & SEED DATA
-- =========================================================

CREATE TABLE IF NOT EXISTS public.certifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  organizer text NOT NULL,
  year text NOT NULL,
  category text NOT NULL,
  badge_name text NOT NULL,
  badge_icon text NOT NULL,
  link text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

TRUNCATE TABLE public.certifications RESTART IDENTITY CASCADE;

INSERT INTO public.certifications (id, name, organizer, year, category, badge_name, badge_icon, link) VALUES (
  1,
  'Gemini Certified — Generative AI',
  'Google',
  '2024',
  'ai',
  'Gemini Academy',
  '/assets/Gemini_compressed.webp',
  NULL
);

INSERT INTO public.certifications (id, name, organizer, year, category, badge_name, badge_icon, link) VALUES (
  2,
  'ACA Cloud Computing Certification',
  'Alibaba Cloud',
  '2024',
  'cloud',
  'ACA Cloud',
  '/assets/ACA_compressed.webp',
  NULL
);

INSERT INTO public.certifications (id, name, organizer, year, category, badge_name, badge_icon, link) VALUES (
  3,
  'Google Cloud Computing Foundation',
  'Google Cloud',
  '2024',
  'cloud',
  'GCP Foundations',
  '/assets/GCP_compressed.webp',
  NULL
);

INSERT INTO public.certifications (id, name, organizer, year, category, badge_name, badge_icon, link) VALUES (
  4,
  'Alibaba Cloud Certified Developer',
  'Alibaba Cloud',
  '2024',
  'cloud',
  'Developer Cert',
  '/assets/DEV_compressed.webp',
  NULL
);

INSERT INTO public.certifications (id, name, organizer, year, category, badge_name, badge_icon, link) VALUES (
  5,
  'HTML, CSS, and Javascript for Web Developers',
  'Johns Hopkins University',
  '2023',
  'web',
  'JHU Web Dev',
  '/assets/JohnCer_compressed.webp',
  'https://coursera.org/verify/QJNY8CPX7QZ2'
);

INSERT INTO public.certifications (id, name, organizer, year, category, badge_name, badge_icon, link) VALUES (
  6,
  'Machine Learning Certification',
  'Coursera / Stanford',
  '2024',
  'ai',
  'Machine Learning',
  '/assets/MachineLearning_compressed.webp',
  NULL
);

-- =========================================================
-- 2. PROJECTS TABLE & SEED DATA
-- =========================================================

CREATE TABLE IF NOT EXISTS public.projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  short_title text,
  year text NOT NULL,
  description text NOT NULL,
  category text NOT NULL,
  tags text[] NOT NULL,
  image text NOT NULL,
  github text,
  demo text,
  featured boolean DEFAULT false,
  role text NOT NULL,
  status text DEFAULT 'published'::text NOT NULL,
  summary text NOT NULL,
  content jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

TRUNCATE TABLE public.projects RESTART IDENTITY CASCADE;

INSERT INTO public.projects (id, slug, title, short_title, year, description, category, tags, image, github, demo, featured, role, status, summary, content) VALUES (
  1,
  'mpk-osis-man-purwakarta',
  'Website MPK OSIS MAN Purwakarta',
  'OSIS MAN',
  '2024',
  'A collaborative project developing an official profile website for MPK OSIS MAN Purwakarta with dynamic content management features.',
  'Web Development',
  '{"PHP","MySQL","School Profile","Consulting"}',
  '/assets/mpkosis_compressed.webp',
  NULL,
  'https://mpkosis-manpwk.web.id/',
  true,
  'Full-stack developer and student team contributor',
  'published',
  'A school organization profile website built to make information, programs, and public communication easier to manage.',
  '[{"id":"context","type":"heading","level":2,"text":"Context"},{"id":"intro","type":"paragraph","text":"This project focused on building a practical public website for MPK OSIS MAN Purwakarta. The site needed to present organization information clearly while giving the team a manageable way to publish content."},{"id":"image","type":"image","src":"/assets/mpkosis_compressed.webp","alt":"Website MPK OSIS MAN Purwakarta preview","caption":"Public profile website for the school organization.","align":"wide","size":"full"},{"id":"work","type":"heading","level":2,"text":"What I Built"},{"id":"work-list","type":"list","items":["Designed the website structure for organization profile content.","Built dynamic content management features with PHP and MySQL.","Collaborated with a student team and supported the school AI seminar program."]},{"id":"links","type":"links","items":[{"label":"Live Website","url":"https://mpkosis-manpwk.web.id/"}]}]'::jsonb
);

INSERT INTO public.projects (id, slug, title, short_title, year, description, category, tags, image, github, demo, featured, role, status, summary, content) VALUES (
  2,
  'hedom-heart-rate-oxygen-monitor',
  'HEDOM: Heart Rate & Oxygen Monitor',
  'HEDOM IoT',
  '2024',
  'An innovative IoT device for real-time heart rate and SpO2 monitoring using MAX30102 sensor, ESP8266, and Blynk integration.',
  'IoT / Embedded',
  '{"IoT","ESP8266","Blynk","MAX30102"}',
  '/assets/iot_compressed.webp',
  NULL,
  NULL,
  false,
  'Embedded system developer',
  'published',
  'A compact IoT case study for monitoring heart rate and oxygen saturation with sensor hardware and cloud visualization.',
  '[{"id":"problem","type":"heading","level":2,"text":"Problem"},{"id":"problem-text","type":"paragraph","text":"Health monitoring tools are often expensive or limited to clinical environments. HEDOM explores a more accessible prototype for real-time heart rate and SpO2 monitoring."},{"id":"hero-image","type":"image","src":"/assets/iot_compressed.webp","alt":"HEDOM heart rate and oxygen monitor prototype","caption":"Prototype documentation for the HEDOM IoT device.","align":"wide","size":"full"},{"id":"approach","type":"heading","level":2,"text":"Approach"},{"id":"approach-list","type":"list","items":["Used MAX30102 as the pulse oximetry sensor.","Used ESP8266 as the network-connected microcontroller.","Integrated Blynk for real-time data viewing.","Focused on a simple prototype that could explain the end-to-end telemetry flow."]}]'::jsonb
);

INSERT INTO public.projects (id, slug, title, short_title, year, description, category, tags, image, github, demo, featured, role, status, summary, content) VALUES (
  3,
  'telco-customer-churn-prediction',
  'Telco Customer Churn Prediction',
  'Telco Churn',
  '2024',
  'XGBoost-based churn classification model achieving F1-Score 92.1%, Recall 89.8%, Precision 94.4%, and ROC AUC 99.0% on IBM Telco dataset.',
  'Machine Learning',
  '{"Machine Learning","XGBoost","Python","IBM Dataset"}',
  '/assets/Pembanding_compressed.webp',
  'https://github.com/Rislantrs/Machine-Learning/tree/main/Project%20Telco%20churn',
  NULL,
  false,
  'Machine learning practitioner',
  'published',
  'A churn prediction project using supervised learning to estimate which customers are likely to leave a telco service.',
  '[{"id":"overview","type":"paragraph","text":"This project uses the IBM Telco dataset to build and compare churn classification models. The best result came from XGBoost with strong recall and ROC AUC performance."},{"id":"image","type":"image","src":"/assets/Pembanding_compressed.webp","alt":"Telco churn model comparison chart","caption":"Model comparison and evaluation result.","align":"center","size":"large"},{"id":"results","type":"heading","level":2,"text":"Results"},{"id":"metrics","type":"list","items":["F1-Score: 92.1%","Recall: 89.8%","Precision: 94.4%","ROC AUC: 99.0%"]},{"id":"links","type":"links","items":[{"label":"GitHub Repository","url":"https://github.com/Rislantrs/Machine-Learning/tree/main/Project%20Telco%20churn"}]}]'::jsonb
);

INSERT INTO public.projects (id, slug, title, short_title, year, description, category, tags, image, github, demo, featured, role, status, summary, content) VALUES (
  4,
  'ai-sentiment-analysis-lexicon-based',
  'AI Sentiment Analysis - Lexicon Based',
  'Sentiment AI',
  '2024',
  'YouTube comment sentiment analysis using Lexicon Based method on 1,054 comments with Sastrawi preprocessing and InSet dictionary.',
  'Natural Language Processing',
  '{"NLP","Web Crawling","Python","Sastrawi"}',
  '/assets/lexicon_compressed.webp',
  'https://github.com/Rislantrs/Analisis-Sentimen-Prasiskom3',
  NULL,
  false,
  'NLP analyst',
  'published',
  'A sentiment analysis workflow for Indonesian YouTube comments using preprocessing and lexicon scoring.',
  '[{"id":"overview","type":"paragraph","text":"This project analyzes YouTube comments using an Indonesian lexicon-based approach. It combines crawling, text cleaning, Sastrawi preprocessing, and sentiment scoring with the InSet dictionary."},{"id":"image","type":"image","src":"/assets/lexicon_compressed.webp","alt":"Lexicon based sentiment analysis result","align":"center","size":"large"},{"id":"process","type":"list","items":["Collected 1,054 YouTube comments.","Cleaned and normalized Indonesian text.","Applied stemming with Sastrawi.","Calculated sentiment using the InSet lexicon."]},{"id":"links","type":"links","items":[{"label":"GitHub Repository","url":"https://github.com/Rislantrs/Analisis-Sentimen-Prasiskom3"}]}]'::jsonb
);

INSERT INTO public.projects (id, slug, title, short_title, year, description, category, tags, image, github, demo, featured, role, status, summary, content) VALUES (
  5,
  'sdn-library-network-case-study',
  'SDN - Library Network Case Study',
  'SDN Network',
  '2023',
  'Software Defined Networking implementation using hybrid topology with Ryu controller and Mininet WiFi, testing scalability from 10 to 100 users.',
  'Networking',
  '{"SDN","Ryu Controller","Mininet-WiFi","Hybrid Topo"}',
  '/assets/SDN_compressed.webp',
  NULL,
  NULL,
  false,
  'Network simulation designer',
  'published',
  'A software defined networking simulation that evaluates a hybrid topology for a library network environment.',
  '[{"id":"overview","type":"paragraph","text":"This case study explores SDN design using a Ryu controller and Mininet-WiFi. The network was tested across multiple user scales to observe behavior and scalability."},{"id":"image","type":"image","src":"/assets/SDN_compressed.webp","alt":"SDN library network topology","align":"wide","size":"full"},{"id":"points","type":"list","items":["Built a hybrid topology scenario.","Used Ryu controller for SDN control logic.","Tested scalability from 10 to 100 users."]}]'::jsonb
);

INSERT INTO public.projects (id, slug, title, short_title, year, description, category, tags, image, github, demo, featured, role, status, summary, content) VALUES (
  6,
  'web-ajaib-interactive-digital-platform',
  'WEB AJAIB - Interactive Digital Platform',
  'Web Ajaib',
  '2025',
  'An interactive platform combining entertainment, education, and social awareness in one digital experience powered by Groq Llama3 model.',
  'Web & AI',
  '{"Flask","Groq API","Python","Llama3"}',
  '/assets/Cuplikan layar 2025-11-02 233325_compressed.webp',
  NULL,
  'https://web-ajaib.vercel.app/',
  true,
  'Web and AI integration developer',
  'published',
  'An experimental web platform combining playful interaction, educational content, and AI-powered features.',
  '[{"id":"overview","type":"paragraph","text":"WEB AJAIB was built as an interactive digital experience that blends utility, learning, and entertainment. The project experiments with AI-assisted features through Groq Llama3 integration."},{"id":"image","type":"image","src":"/assets/Cuplikan layar 2025-11-02 233325_compressed.webp","alt":"WEB AJAIB platform preview","align":"wide","size":"full"},{"id":"links","type":"links","items":[{"label":"Live Demo","url":"https://web-ajaib.vercel.app/"}]}]'::jsonb
);

INSERT INTO public.projects (id, slug, title, short_title, year, description, category, tags, image, github, demo, featured, role, status, summary, content) VALUES (
  7,
  'house-price-prediction-catboost',
  'House Price Prediction - CatBoost',
  'CatBoost Price',
  '2024',
  'CatBoost regression model achieving R2 = 0.9930 for house price prediction with feature influence analysis.',
  'Machine Learning',
  '{"Python","CatBoost","Scikit-Learn","Regression"}',
  '/assets/rumah_compressed.webp',
  'https://github.com/Rislantrs/Prasiskom2-Project-Prediksi-Harga-Rumah',
  NULL,
  false,
  'Machine learning practitioner',
  'published',
  'A regression project that predicts house prices and studies which building attributes contribute most strongly.',
  '[{"id":"overview","type":"paragraph","text":"This project uses CatBoost regression for house price prediction. The analysis shows that building quality and total surface area are among the strongest price drivers."},{"id":"image","type":"image","src":"/assets/rumah_compressed.webp","alt":"House price prediction analysis","align":"center","size":"large"},{"id":"links","type":"links","items":[{"label":"GitHub Repository","url":"https://github.com/Rislantrs/Prasiskom2-Project-Prediksi-Harga-Rumah"}]}]'::jsonb
);

INSERT INTO public.projects (id, slug, title, short_title, year, description, category, tags, image, github, demo, featured, role, status, summary, content) VALUES (
  8,
  'hapino-happy-arduino',
  'HAPINO - Happy Arduino',
  'HAPINO IoT',
  '2023',
  'Creative Arduino Uno project that plays Happy Birthday musical note, sweeps physical servo gates, lights RGB LEDs, and displays LCD messages on button press.',
  'IoT / Embedded',
  '{"Arduino","IoT","Embedded System","C++"}',
  '/assets/Uno_compressed.webp',
  'https://drive.google.com/drive/u/1/folders/1tAoaLIUd6-Hh7cDGcS7JON4q5bH5It3y',
  NULL,
  false,
  'Embedded system builder',
  'published',
  'A playful Arduino prototype combining sound, servo movement, RGB LED feedback, and LCD interaction.',
  '[{"id":"overview","type":"paragraph","text":"HAPINO combines several Arduino components into one interactive prototype. It reacts to button input by playing a melody, moving servo gates, lighting RGB LEDs, and showing LCD messages."},{"id":"image","type":"image","src":"/assets/Uno_compressed.webp","alt":"Arduino Uno project preview","align":"center","size":"large"},{"id":"links","type":"links","items":[{"label":"Project Files","url":"https://drive.google.com/drive/u/1/folders/1tAoaLIUd6-Hh7cDGcS7JON4q5bH5It3y"}]}]'::jsonb
);

INSERT INTO public.projects (id, slug, title, short_title, year, description, category, tags, image, github, demo, featured, role, status, summary, content) VALUES (
  9,
  'lsb-steganography-matlab',
  'LSB Steganography - MATLAB',
  'MATLAB Stego',
  '2023',
  'Least Significant Bit steganography implementation for embedding and extracting hidden text messages in digital cover images.',
  'Cyber Security',
  '{"MATLAB","Steganography","Cryptography","Security"}',
  '/assets/stego_compressed.webp',
  'https://github.com/Rislantrs/Steganografi',
  NULL,
  false,
  'Security algorithm implementer',
  'published',
  'A MATLAB implementation of LSB steganography for hiding and extracting text inside cover images.',
  '[{"id":"overview","type":"paragraph","text":"This project implements Least Significant Bit steganography in MATLAB. It embeds hidden text into cover images and evaluates quality using PSNR and SSIM."},{"id":"image","type":"image","src":"/assets/stego_compressed.webp","alt":"LSB steganography project preview","align":"center","size":"large"},{"id":"links","type":"links","items":[{"label":"GitHub Repository","url":"https://github.com/Rislantrs/Steganografi"}]}]'::jsonb
);

-- =========================================================
-- 3. FORUM TABLES (FOR CHAT & DISCUSSION)
-- =========================================================

CREATE TABLE IF NOT EXISTS public.forum_threads (
  id text PRIMARY KEY,
  title text NOT NULL,
  author text NOT NULL,
  avatar text DEFAULT '💬'::text NOT NULL,
  category text NOT NULL,
  rating integer,
  content text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.forum_comments (
  id text PRIMARY KEY,
  thread_id text NOT NULL REFERENCES public.forum_threads(id) ON DELETE CASCADE,
  author text NOT NULL,
  avatar text DEFAULT '💬'::text NOT NULL,
  content text NOT NULL,
  parent_id text REFERENCES public.forum_comments(id) ON DELETE CASCADE,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_forum_comments_thread ON public.forum_comments(thread_id);
CREATE INDEX IF NOT EXISTS idx_forum_comments_parent ON public.forum_comments(parent_id);
